query AllEvents {
	newWorkRequest: events(
		where: {
			account_address: {}
			indexed_type: {
				_eq: "0x9476528b38675eaf7fcc4d18c9472f22efd24532cad25a27794c6f7300df06cc::proxirun::OnNewWorkRequest"
			}
		}
	) {
		data
	}

	workRequestCompleted: events(
		where: {
			account_address: {}
			indexed_type: {
				_eq: "0x9476528b38675eaf7fcc4d18c9472f22efd24532cad25a27794c6f7300df06cc::proxirun::OnWorkRequestCompleted"
			}
		}
	) {
		data
	}

	newBids: events(
		where: {
			account_address: {}
			indexed_type: {
				_eq: "0x9476528b38675eaf7fcc4d18c9472f22efd24532cad25a27794c6f7300df06cc::proxirun::OnNewWorkRequestBid"
			}
		}
	) {
		data
	}

	bidWons: events(
		where: {
			account_address: {}
			indexed_type: {
				_eq: "0x9476528b38675eaf7fcc4d18c9472f22efd24532cad25a27794c6f7300df06cc::proxirun::OnBidWon"
			}
		}
	) {
		data
	}

	auctionFailures: events(
		where: {
			account_address: {}
			indexed_type: {
				_eq: "0x9476528b38675eaf7fcc4d18c9472f22efd24532cad25a27794c6f7300df06cc::proxirun::OnAuctionFailure"
			}
		}
	) {
		data
	}
}
